### ISSUE TITLE
Optional input files

### ISSUE THREAD

**Issue by flying-sheep** [FASTGenomics/fastgenomics-py#17]
If there are optional features toggleable via parameter, one might want to not supply an unnecessary file.

An app developer should be able to mark a file as optional so that `get_input_path` doesn’t raise errors if it’s not in the mapping and/or doesn’t exist.

**Comment by hensing** [comment]
Added in commit https://github.com/FASTGenomics/fastgenomics-py/commit/1932fee92c3f2e477802a336cfc74cad11085074
